### ISSUE TITLE
egicli endpoint env should allow to directly set the environment

### ISSUE THREAD

**Issue by gwarf** [EGI-Federation/egicli#10]
`egicli endpoint env` should allow to directly set the environment: currently it prints what should be set but doesn't set it and one can use it like this:

```sh
egicli endpoint env --site XXXX --project-id yyyyyyy | tee cloud-env.sh
source cloud-env.sh
```

But when the token will have expired it will be required to re-rerun the command and re-source the env file. It would be convenient to be able to do

```sh
egicli endpoint env --site XXXX --project-id yyyyyyy --set
# Another alternative could be to have a setenv subcommand
egicli endpoint setenv --site XXXX --project-id yyyyyyy
# with potentially a --print option to replace the env command
egicli endpoint setenv --site XXXX --project-id yyyyyyy --print
```

**Comment by enolfc** [comment]
I am using the command as follows:

```
eval "$(egicli endpoint env --site XXXX --project-id yyyyyyy)"
```

which seems to work fine

In fish I'm using

```
egicli endpoint env --site XXXX --project-id yyyyyyy | source
```

which is also fine

Can we change the environment of the process that forks the egicli?

**Comment by gwarf** [comment]
Duh, of course you cannot do things like this, it's certainly not possible to alter the parent's environment. :(
So `eval` or something using source are the alternatives indeed.
