### ISSUE TITLE
Hotfix auth 

### ISSUE THREAD

**Issue by UkrainskyiRostyslav** [EGI-Federation/egicli#23]
checkin.py
```
auth=None
if checkin_client_secret:
    auth=(checkin_client_id, checkin_client_secret)
    refresh_data.update({"client_secret": checkin_client_secret})
r = requests.post(token_url, auth=None, data=refresh_data)
r.raise_for_status()
return r.json()
```
`r = requests.post(token_url, auth=None, data=refresh_data)`

should be like this:

`r = requests.post(token_url, auth, data=refresh_data)`

**Comment by enolfc** [comment]
good catch!

Can you submit a PR? I will approve it right away

**Comment by UkrainskyiRostyslav** [comment]
> checkin.py
> 
> ```
> auth=None
> if checkin_client_secret:
>     auth=(checkin_client_id, checkin_client_secret)
>     refresh_data.update({"client_secret": checkin_client_secret})
> r = requests.post(token_url, auth=None, data=refresh_data)
> r.raise_for_status()
> return r.json()
> ```
> 
> ```r = requests.post(token_url, auth=None, data=refresh_data)```
> 
> should be like this:
> 
> `r = requests.post(token_url, auth, data=refresh_data)`

**Comment by UkrainskyiRostyslav** [comment]
ERROR: Permission to EGI-Federation/egicli.git denied to UkrainskyiRostyslav.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by enolfc** [comment]
you need to fork and submit the PR from there. If too much of a hassle I can create the patch myself.

**Comment by kstepanovdev** [comment]
Hello @enolfc 

I've created the PR, so feel free to review it. If there are any additional actions required from me (e.g. additional notes in PR's description or commits' style), please leave me a comment.
